### PR TITLE
Actions unified

### PR DESCRIPTION
**Pull request by PaulJonasJost**
- Unified Icons
- All Actions created in one place (almost all)
- Usage of actions throughout code

Missing `will be addressed in combination with other PR`:
- Upload data matrix
- Uploading single tables
-> Will be fixed when Upload will be unified
- Adding deleting rows in edit menu
-> Will be adjusted when adding/deleting rows/columns will be fixed

### CODE REVIEW

**Comment by PaulJonasJost** [comment]
will wait for #29 to be merged

**Comment by fbergmann** [comment]
@PaulJonasJost so 'open' is still called 'open yaml configuration', i would just have 'Open', which additionally allows for the opening of all files. And introduce the 'New' option we talked about. 

I like the tiny icons next to the filter better, but cant read them here. I woudl make the filter symbol smaller and the text a bit bigger: 
image

**Review by fbergmann — APPROVED** [review]

**Comment by PaulJonasJost** [comment]
> @PaulJonasJost so 'open' is still called 'open yaml configuration', i would just have 'Open', which additionally allows for the opening of all files. And introduce the 'New' option we talked about.


Agreed, will adjust this when I Unify all upload. Will be a separate PR.

**Comment by PaulJonasJost** [comment]
Switched Letter and Filter symbol, should be better readable now 👍🏼

**Pull request merged**
