### PR TITLE
Open files from command line

### PR DESCRIPTION
**Pull request by fbergmann**
For discussion on Thu, this PR changes the gui a bit, so that files can be passed along as command line args (either model or yaml file so far) or if dropped onto the GUI

further changes on gui needed: 

- application name should list currently loaded name
- the model changes from (https://github.com/PaulJonasJost/PEtab_GUI/pull/28) should be merged in first
- new open functions should ask for save if the old model was changed

- currently there is a hack in there for the main window to prompt the controller to open a file

### CODE REVIEW

**Review by PaulJonasJost — CHANGES_REQUESTED** [review]
Dont know enough about the drag and drop, hence this looks good to me, can only report the mistakes I got by testing:

- Starting with example from command line for like a charm 👍🏼 
- Drag and drop of a yaml file results in a segmentation fault (other message I attached the start of the report). The fault only occurs when being in the `Data Tables`-tab. When dropping it (at appropriate place in the `SBML Model` tab, the model loads in, thus from slight debugging it seems to work). Could this have to do with the fact that the `Data Table`-Tab is a own window?
- Dragging either file into the `SBML Model` tab into the TextEdit widgets just adds the filepath in there. Dragging it into the general frame works 👍🏼

**Comment by PaulJonasJost** [comment]
Attached the report from the segmentation fault
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               python3.12 [81278]
Path:                  /Users/USER/Documents/*/python
Identifier:            python3.12
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        zsh [34248]
Responsible:           pycharm [7941]
User ID:               501

Date/Time:             2024-11-25 11:27:42.6461 +0100
OS Version:            macOS 15.0.1 (24A348)
Report Version:        12
Bridge OS Version:     9.0 (22P353)
Anonymous UUID:        93D861B6-C895-D09A-2127-518E843D6BD7

Sleep/Wake UUID:       090CAC11-96FC-4715-80AC-004CA61902CD

Time Awake Since Boot: 110000 seconds
Time Since Wake:       80193 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [81278]

VM Region Info: 0 is not in any region.  Bytes before following region: 4528594944
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10dece000-10decf000    [    4K] r-x/r-x SM=COW  /Users/USER/*/python3.12

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   QtWidgets                     	       0x10fcc4165 0x10f9a3000 + 3281253
1   QtWidgets                     	       0x10fcc6459 QTableView::paintEvent(QPaintEvent*) + 1993
2   QtWidgets                     	       0x10fa01074 QWidget::event(QEvent*) + 1252
3   QtWidgets                     	       0x10fa95eab QFrame::event(QEvent*) + 43
4   QtWidgets                     	       0x10fc6b65d QAbstractItemView::viewportEvent(QEvent*) + 1245
5   QtCore                        	       0x111a12d31 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 241
6   QtWidgets                     	       0x10f9af063 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 227
7   QtWidgets                     	       0x10f9afe82 QApplication::notify(QObject*, QEvent*) + 498
8   QtCore                        	       0x111a12a84 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
9   QtWidgets                     	       0x10f9f21bd QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 3933
10  QtWidgets                     	       0x10f9f9d6f QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1007
11  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
12  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
13  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
14  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
15  QtWidgets                     	       0x10f9f22f8 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4248
16  QtWidgets                     	       0x10f9f9d6f QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1007
17  QtWidgets                     	       0x10f9f22f8 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4248
18  QtWidgets                     	       0x10f9f9d6f QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1007
19  QtWidgets                     	       0x10f9f22f8 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4248
20  QtWidgets                     	       0x10f9f9d6f QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1007
21  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
22  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
23  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
24  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
25  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
26  QtWidgets                     	       0x10f9f9c2a QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 682
27  QtWidgets                     	       0x10f9f22f8 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4248
28  QtWidgets                     	       0x10f9f9d6f QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1007
29  QtWidgets                     	       0x10f9f22f8 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4248
30  QtWidgets                     	       0x10f9f9d6f QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1007
31  QtWidgets                     	       0x10f9f22f8 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4248
32  QtWidgets                     	       0x10f9f9d6f QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1007
33  QtWidgets                     	       0x10f9f22f8 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4248
34  QtWidgets                     	       0x10fa1402d QWidgetRepaintManager::paintAndFlush() + 5229
35  QtWidgets                     	       0x10fa14317 QWidgetRepaintManager::sync() + 247
36  QtWidgets                     	       0x10fa0129b QWidget::event(QEvent*) + 1803
37  QtWidgets                     	       0x10fb44d15 QMainWindow::event(QEvent*) + 837
38  QtWidgets                     	       0x10f9af077 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 247
39  QtWidgets                     	       0x10f9afe82 QApplication::notify(QObject*, QEvent*) + 498
40  QtCore                        	       0x111a12a84 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
41  QtCore                        	       0x111a13cda QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 1530
42  libqcocoa.dylib               	       0x143ee65ab 0x143ecc000 + 107947
43  libqcocoa.dylib               	       0x143ee755f 0x143ecc000 + 111967
... etc
```

**Comment by fbergmann** [comment]
I might need more information as to what kind of file you dragged. It works fine here on Windows, though I only dragged the yaml / sbml files since we didn't add the support for tsv's yet. 

There stack trace you are sending is unrelated, about something happening while rendering. That would happen if the table model somehow would return stuff that doesn't make sense to Qt. 

Can you try and reproduce what file you dragged when where and that would help us to debug this.

**Review by PaulJonasJost — APPROVED** [review]
I think given that some yaml files actually work and if this works on your computer (with giordano), I am fine with merging, though it would be interesting to know why this happens nonetheless. Is it possible to add something like a tooltip of the event that is going to be executed to show people the difference of dragging it into a `TextEdit` vs the general window?

**Comment by fbergmann** [comment]
I've debugged it in so far, that i can tell you that the issue is with the measurement file. The models loads without crashing if i just skip the file. I've noticed that the position of the preequilib column is different on that measurement file. Anyways, lets merge this PR and open a new one for the crash.

**Pull request merged**
